name: Test and deploy

on: [push]

env:
  HOST: 142.93.169.227
  REMOTE_PATH: /root/volumes/static/imvesters-app
  ZIPFILE: imvesters-app.zip

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: env var
        run: |
          echo "GITHUB_SHA=$GITHUB_SHA"
          echo "GITHUB_SHA_SHORT=$GITHUB_SHA_SHORT"
      - name: Install Packages
        run: yarn install
      #- run: yarn test
      - name: Build page
        run: REACT_APP_GIT_SHA=$GITHUB_SHA yarn build
     
